/**
 * Production server: single port, no Vite.
 *  - `/api/*`      -> Elysia
 *  - `/assets/*`   -> hashed immutable client assets from build/client
 *  - other files   -> static files from build/client (favicon, etc.)
 *  - everything else -> React Router SSR handler from the compiled server build
 *
 * Run after `bun run build`.
 *
 * Single-file binary mode (bun build --compile --asset ./build/client):
 *   Bun bundles this file and follows the static import of the SSR bundle,
 *   pulling in @react-router/node and all other deps into the binary.
 *   Client assets are embedded via --asset and served via import.meta.dir.
 */
import path from 'node:path';
import { createRequestHandler, type ServerBuild } from 'react-router';
// Generated by `react-router build` (typed via server/types/ssr-build.d.ts). In
// `bun build --compile` mode Bun follows this static import and bundles the SSR
// module + all its dependencies (@react-router/node, react-dom, etc.) into the binary.
import * as ssrBuild from '../build/server/index.js';
import bundledChangelog from '../CHANGELOG.md' with { type: 'text' };
import { api } from './api';
import { newRequestId } from './api-error';
import { registerBundledChangelog } from './changelog';
import { bootEngines, exitOnShutdownSignals } from './engines/boot';
import { env } from './env';
import { errorResponse } from './error-page';
import { needsLongTimeout, serveLimits } from './http-limits';
import { isHttpProbe, probeResponse } from './http-probes';
import { logger } from './logger';
import { stampClientIp } from './middleware/client-ip';
import { recordVisit } from './middleware/visitor';
import { agentDocResponse, isAgentDoc } from './readme';
import { isSeoFile, seoResponse } from './seo';
import { getBranding } from './settings-branding';
import { maintenanceGate } from './settings-maintenance';

registerBundledChangelog(bundledChangelog);

const build = ssrBuild as unknown as ServerBuild;
const handler = createRequestHandler(build, 'production');

// In standalone binary: import.meta.dir = /$bunfs/root, assets embedded as 'client/' (stripped from ./build/client).
// In script mode: import.meta.dir = /path/to/server/, assets at ../build/client.
const CLIENT_DIR = Bun.isStandaloneExecutable
  ? `${path.join(import.meta.dir, 'client')}/`
  : `${path.join(import.meta.dir, '../build/client')}/`;

// Engines are lazy: this registers them without starting a child or loading a model.
bootEngines();
exitOnShutdownSignals();

const server = Bun.serve({
  port: env.PORT,
  ...serveLimits(),
  async fetch(request, bunServer) {
    const url = new URL(request.url);
    // Long transcriptions, queued speech/SSE and warmups send nothing for minutes.
    if (needsLongTimeout(url.pathname)) bunServer.timeout(request, 0);
    // Socket IP → internal header, so rate limiting and analytics see the real client.
    stampClientIp(request, bunServer.requestIP(request)?.address);

    // API + auth.
    if (url.pathname.startsWith('/api')) {
      return api.handle(request);
    }

    // Browser/devtools probes — never SSR, never counted as a visit.
    if (isHttpProbe(url.pathname)) return probeResponse(url.pathname);

    // Plain-text docs for agents (/README.md, /llms.txt) — from the bundled README.
    if (isAgentDoc(url.pathname)) return agentDocResponse(request, url.pathname);

    // Crawler files (/robots.txt, /sitemap.xml) built from APP_URL.
    if (isSeoFile(url.pathname)) return seoResponse(request, url.pathname);

    // Static client assets.
    const filePath = CLIENT_DIR + url.pathname.replace(/^\/+/, '');
    const file = Bun.file(filePath);
    if (url.pathname !== '/' && (await file.exists())) {
      const immutable = url.pathname.startsWith('/assets/');
      return new Response(file, {
        headers: immutable
          ? { 'Cache-Control': 'public, max-age=31536000, immutable' }
          : { 'Cache-Control': 'public, max-age=3600' },
      });
    }

    // Maintenance mode answers before SSR (and is not counted as a visit).
    const blocked = await maintenanceGate(request, (await getBranding()).appName);
    if (blocked) return blocked;

    // SSR. Record page visit (fire-and-forget — must not block response).
    void recordVisit(request);
    try {
      return await handler(request);
    } catch (err) {
      // React Router renders its own error boundary for route errors; this only
      // catches a crash of the shell itself, so the user still gets a real page.
      const requestId = newRequestId();
      logger.error({ err, requestId, path: url.pathname }, 'SSR error');
      return errorResponse({ status: 500, requestId });
    }
  },
});

logger.info(`\u{1F680} Makuro production server on http://localhost:${server.port}`);
